/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { AccountDto, PatchAccountDto } from "../../model";

import { createInstance } from "../../instance";
import type { ErrorType, BodyType } from "../../instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Добавить доп. информацию профиля
 */
export const accountControllerGetAccount = (
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<AccountDto>(
    { url: `/api/account`, method: "GET", signal },
    options,
  );
};

export const getAccountControllerGetAccountInfiniteQueryKey = () => {
  return ["infinite", `/api/account`] as const;
};

export const getAccountControllerGetAccountQueryKey = () => {
  return [`/api/account`] as const;
};

export const getAccountControllerGetAccountInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof accountControllerGetAccount>>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof accountControllerGetAccount>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAccountControllerGetAccountInfiniteQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof accountControllerGetAccount>>
  > = ({ signal }) => accountControllerGetAccount(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof accountControllerGetAccount>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AccountControllerGetAccountInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof accountControllerGetAccount>>
>;
export type AccountControllerGetAccountInfiniteQueryError = ErrorType<unknown>;

export function useAccountControllerGetAccountInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof accountControllerGetAccount>>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof accountControllerGetAccount>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetAccount>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetAccount>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAccountControllerGetAccountInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof accountControllerGetAccount>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof accountControllerGetAccount>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetAccount>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetAccount>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAccountControllerGetAccountInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof accountControllerGetAccount>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof accountControllerGetAccount>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Добавить доп. информацию профиля
 */

export function useAccountControllerGetAccountInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof accountControllerGetAccount>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof accountControllerGetAccount>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getAccountControllerGetAccountInfiniteQueryOptions(options);

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getAccountControllerGetAccountQueryOptions = <
  TData = Awaited<ReturnType<typeof accountControllerGetAccount>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof accountControllerGetAccount>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAccountControllerGetAccountQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof accountControllerGetAccount>>
  > = ({ signal }) => accountControllerGetAccount(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof accountControllerGetAccount>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AccountControllerGetAccountQueryResult = NonNullable<
  Awaited<ReturnType<typeof accountControllerGetAccount>>
>;
export type AccountControllerGetAccountQueryError = ErrorType<unknown>;

export function useAccountControllerGetAccount<
  TData = Awaited<ReturnType<typeof accountControllerGetAccount>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof accountControllerGetAccount>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetAccount>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetAccount>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAccountControllerGetAccount<
  TData = Awaited<ReturnType<typeof accountControllerGetAccount>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof accountControllerGetAccount>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof accountControllerGetAccount>>,
          TError,
          Awaited<ReturnType<typeof accountControllerGetAccount>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAccountControllerGetAccount<
  TData = Awaited<ReturnType<typeof accountControllerGetAccount>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof accountControllerGetAccount>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Добавить доп. информацию профиля
 */

export function useAccountControllerGetAccount<
  TData = Awaited<ReturnType<typeof accountControllerGetAccount>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof accountControllerGetAccount>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAccountControllerGetAccountQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Обновить доп. информацию профиля
 */
export const accountControllerPatchAccount = (
  patchAccountDto: BodyType<PatchAccountDto>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<PatchAccountDto>(
    {
      url: `/api/account`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: patchAccountDto,
      signal,
    },
    options,
  );
};

export const getAccountControllerPatchAccountMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountControllerPatchAccount>>,
    TError,
    { data: BodyType<PatchAccountDto> },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountControllerPatchAccount>>,
  TError,
  { data: BodyType<PatchAccountDto> },
  TContext
> => {
  const mutationKey = ["accountControllerPatchAccount"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountControllerPatchAccount>>,
    { data: BodyType<PatchAccountDto> }
  > = (props) => {
    const { data } = props ?? {};

    return accountControllerPatchAccount(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountControllerPatchAccountMutationResult = NonNullable<
  Awaited<ReturnType<typeof accountControllerPatchAccount>>
>;
export type AccountControllerPatchAccountMutationBody =
  BodyType<PatchAccountDto>;
export type AccountControllerPatchAccountMutationError = ErrorType<unknown>;

/**
 * @summary Обновить доп. информацию профиля
 */
export const useAccountControllerPatchAccount = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof accountControllerPatchAccount>>,
      TError,
      { data: BodyType<PatchAccountDto> },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof accountControllerPatchAccount>>,
  TError,
  { data: BodyType<PatchAccountDto> },
  TContext
> => {
  return useMutation(
    getAccountControllerPatchAccountMutationOptions(options),
    queryClient,
  );
};
