/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CompanyControllerFindAll200,
  CompanyControllerFindAllParams,
  CreateCompanyDto,
  UpdateCompanyDto,
} from "../../model";

import { createInstance } from "../../instance";
import type { ErrorType, BodyType } from "../../instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Добавить информацию о новой компании-клиента
 */
export const companyControllerCreate = (
  createCompanyDto: BodyType<CreateCompanyDto>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<CreateCompanyDto>(
    {
      url: `/api/company`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCompanyDto,
      signal,
    },
    options,
  );
};

export const getCompanyControllerCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyControllerCreate>>,
    TError,
    { data: BodyType<CreateCompanyDto> },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyControllerCreate>>,
  TError,
  { data: BodyType<CreateCompanyDto> },
  TContext
> => {
  const mutationKey = ["companyControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyControllerCreate>>,
    { data: BodyType<CreateCompanyDto> }
  > = (props) => {
    const { data } = props ?? {};

    return companyControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerCreate>>
>;
export type CompanyControllerCreateMutationBody = BodyType<CreateCompanyDto>;
export type CompanyControllerCreateMutationError = ErrorType<unknown>;

/**
 * @summary Добавить информацию о новой компании-клиента
 */
export const useCompanyControllerCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyControllerCreate>>,
      TError,
      { data: BodyType<CreateCompanyDto> },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyControllerCreate>>,
  TError,
  { data: BodyType<CreateCompanyDto> },
  TContext
> => {
  return useMutation(
    getCompanyControllerCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Получить список компаний (курсорная пагинация по ID)
 */
export const companyControllerFindAll = (
  params: CompanyControllerFindAllParams,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<CompanyControllerFindAll200>(
    { url: `/api/company`, method: "GET", params, signal },
    options,
  );
};

export const getCompanyControllerFindAllInfiniteQueryKey = (
  params?: CompanyControllerFindAllParams,
) => {
  return ["infinite", `/api/company`, ...(params ? [params] : [])] as const;
};

export const getCompanyControllerFindAllQueryKey = (
  params?: CompanyControllerFindAllParams,
) => {
  return [`/api/company`, ...(params ? [params] : [])] as const;
};

export const getCompanyControllerFindAllInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof companyControllerFindAll>>,
    CompanyControllerFindAllParams["skip"]
  >,
  TError = ErrorType<unknown>,
>(
  params: CompanyControllerFindAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindAll>>,
        TError,
        TData,
        QueryKey,
        CompanyControllerFindAllParams["skip"]
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getCompanyControllerFindAllInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerFindAll>>,
    QueryKey,
    CompanyControllerFindAllParams["skip"]
  > = ({ signal, pageParam }) =>
    companyControllerFindAll(
      { ...params, skip: pageParam || params?.["skip"] },
      requestOptions,
      signal,
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof companyControllerFindAll>>,
    TError,
    TData,
    QueryKey,
    CompanyControllerFindAllParams["skip"]
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerFindAllInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerFindAll>>
>;
export type CompanyControllerFindAllInfiniteQueryError = ErrorType<unknown>;

export function useCompanyControllerFindAllInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof companyControllerFindAll>>,
    CompanyControllerFindAllParams["skip"]
  >,
  TError = ErrorType<unknown>,
>(
  params: CompanyControllerFindAllParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindAll>>,
        TError,
        TData,
        QueryKey,
        CompanyControllerFindAllParams["skip"]
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof companyControllerFindAll>>,
          QueryKey
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerFindAllInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof companyControllerFindAll>>,
    CompanyControllerFindAllParams["skip"]
  >,
  TError = ErrorType<unknown>,
>(
  params: CompanyControllerFindAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindAll>>,
        TError,
        TData,
        QueryKey,
        CompanyControllerFindAllParams["skip"]
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof companyControllerFindAll>>,
          QueryKey
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerFindAllInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof companyControllerFindAll>>,
    CompanyControllerFindAllParams["skip"]
  >,
  TError = ErrorType<unknown>,
>(
  params: CompanyControllerFindAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindAll>>,
        TError,
        TData,
        QueryKey,
        CompanyControllerFindAllParams["skip"]
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить список компаний (курсорная пагинация по ID)
 */

export function useCompanyControllerFindAllInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof companyControllerFindAll>>,
    CompanyControllerFindAllParams["skip"]
  >,
  TError = ErrorType<unknown>,
>(
  params: CompanyControllerFindAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindAll>>,
        TError,
        TData,
        QueryKey,
        CompanyControllerFindAllParams["skip"]
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCompanyControllerFindAllInfiniteQueryOptions(
    params,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getCompanyControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: CompanyControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerFindAll>>
  > = ({ signal }) => companyControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof companyControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerFindAll>>
>;
export type CompanyControllerFindAllQueryError = ErrorType<unknown>;

export function useCompanyControllerFindAll<
  TData = Awaited<ReturnType<typeof companyControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: CompanyControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof companyControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerFindAll<
  TData = Awaited<ReturnType<typeof companyControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: CompanyControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof companyControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerFindAll<
  TData = Awaited<ReturnType<typeof companyControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: CompanyControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить список компаний (курсорная пагинация по ID)
 */

export function useCompanyControllerFindAll<
  TData = Awaited<ReturnType<typeof companyControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: CompanyControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCompanyControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Получить компанию по ID
 */
export const companyControllerFindOne = (
  id: number,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<CreateCompanyDto>(
    { url: `/api/company/${id}`, method: "GET", signal },
    options,
  );
};

export const getCompanyControllerFindOneInfiniteQueryKey = (id: number) => {
  return ["infinite", `/api/company/${id}`] as const;
};

export const getCompanyControllerFindOneQueryKey = (id: number) => {
  return [`/api/company/${id}`] as const;
};

export const getCompanyControllerFindOneInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof companyControllerFindOne>>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerFindOneInfiniteQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerFindOne>>
  > = ({ signal }) => companyControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof companyControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerFindOneInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerFindOne>>
>;
export type CompanyControllerFindOneInfiniteQueryError = ErrorType<unknown>;

export function useCompanyControllerFindOneInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof companyControllerFindOne>>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof companyControllerFindOne>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerFindOneInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof companyControllerFindOne>>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof companyControllerFindOne>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerFindOneInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof companyControllerFindOne>>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить компанию по ID
 */

export function useCompanyControllerFindOneInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof companyControllerFindOne>>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCompanyControllerFindOneInfiniteQueryOptions(
    id,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getCompanyControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof companyControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompanyControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companyControllerFindOne>>
  > = ({ signal }) => companyControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof companyControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CompanyControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerFindOne>>
>;
export type CompanyControllerFindOneQueryError = ErrorType<unknown>;

export function useCompanyControllerFindOne<
  TData = Awaited<ReturnType<typeof companyControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof companyControllerFindOne>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerFindOne<
  TData = Awaited<ReturnType<typeof companyControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof companyControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof companyControllerFindOne>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCompanyControllerFindOne<
  TData = Awaited<ReturnType<typeof companyControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить компанию по ID
 */

export function useCompanyControllerFindOne<
  TData = Awaited<ReturnType<typeof companyControllerFindOne>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companyControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCompanyControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Изменить данные о компании по ID
 */
export const companyControllerUpdate = (
  id: number,
  updateCompanyDto: BodyType<UpdateCompanyDto>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    {
      url: `/api/company/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateCompanyDto,
      signal,
    },
    options,
  );
};

export const getCompanyControllerUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyControllerUpdate>>,
    TError,
    { id: number; data: BodyType<UpdateCompanyDto> },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyControllerUpdate>>,
  TError,
  { id: number; data: BodyType<UpdateCompanyDto> },
  TContext
> => {
  const mutationKey = ["companyControllerUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyControllerUpdate>>,
    { id: number; data: BodyType<UpdateCompanyDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return companyControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerUpdate>>
>;
export type CompanyControllerUpdateMutationBody = BodyType<UpdateCompanyDto>;
export type CompanyControllerUpdateMutationError = ErrorType<unknown>;

/**
 * @summary Изменить данные о компании по ID
 */
export const useCompanyControllerUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyControllerUpdate>>,
      TError,
      { id: number; data: BodyType<UpdateCompanyDto> },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyControllerUpdate>>,
  TError,
  { id: number; data: BodyType<UpdateCompanyDto> },
  TContext
> => {
  return useMutation(
    getCompanyControllerUpdateMutationOptions(options),
    queryClient,
  );
};
export const companyControllerRemove = (
  id: number,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    { url: `/api/company/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getCompanyControllerRemoveMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof companyControllerRemove>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof companyControllerRemove>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["companyControllerRemove"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof companyControllerRemove>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return companyControllerRemove(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CompanyControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof companyControllerRemove>>
>;

export type CompanyControllerRemoveMutationError = ErrorType<unknown>;

export const useCompanyControllerRemove = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof companyControllerRemove>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof companyControllerRemove>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(
    getCompanyControllerRemoveMutationOptions(options),
    queryClient,
  );
};
