/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */
import { useInfiniteQuery, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ChatControllerGetMessagesParams,
  ChatResponseDto,
  MessageResponseDto,
} from "../../model";

import { createInstance } from "../../instance";
import type { ErrorType } from "../../instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Список моих чатов
 */
export const chatControllerGetMyChats = (
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<ChatResponseDto[]>(
    { url: `/api/chat/my-chats`, method: "GET", signal },
    options,
  );
};

export const getChatControllerGetMyChatsInfiniteQueryKey = () => {
  return ["infinite", `/api/chat/my-chats`] as const;
};

export const getChatControllerGetMyChatsQueryKey = () => {
  return [`/api/chat/my-chats`] as const;
};

export const getChatControllerGetMyChatsInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof chatControllerGetMyChats>>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof chatControllerGetMyChats>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getChatControllerGetMyChatsInfiniteQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof chatControllerGetMyChats>>
  > = ({ signal }) => chatControllerGetMyChats(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof chatControllerGetMyChats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChatControllerGetMyChatsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof chatControllerGetMyChats>>
>;
export type ChatControllerGetMyChatsInfiniteQueryError = ErrorType<unknown>;

export function useChatControllerGetMyChatsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof chatControllerGetMyChats>>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMyChats>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerGetMyChats>>,
          TError,
          Awaited<ReturnType<typeof chatControllerGetMyChats>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatControllerGetMyChatsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof chatControllerGetMyChats>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMyChats>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerGetMyChats>>,
          TError,
          Awaited<ReturnType<typeof chatControllerGetMyChats>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatControllerGetMyChatsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof chatControllerGetMyChats>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMyChats>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Список моих чатов
 */

export function useChatControllerGetMyChatsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof chatControllerGetMyChats>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMyChats>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getChatControllerGetMyChatsInfiniteQueryOptions(options);

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getChatControllerGetMyChatsQueryOptions = <
  TData = Awaited<ReturnType<typeof chatControllerGetMyChats>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof chatControllerGetMyChats>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getChatControllerGetMyChatsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof chatControllerGetMyChats>>
  > = ({ signal }) => chatControllerGetMyChats(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof chatControllerGetMyChats>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChatControllerGetMyChatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof chatControllerGetMyChats>>
>;
export type ChatControllerGetMyChatsQueryError = ErrorType<unknown>;

export function useChatControllerGetMyChats<
  TData = Awaited<ReturnType<typeof chatControllerGetMyChats>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMyChats>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerGetMyChats>>,
          TError,
          Awaited<ReturnType<typeof chatControllerGetMyChats>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatControllerGetMyChats<
  TData = Awaited<ReturnType<typeof chatControllerGetMyChats>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMyChats>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerGetMyChats>>,
          TError,
          Awaited<ReturnType<typeof chatControllerGetMyChats>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatControllerGetMyChats<
  TData = Awaited<ReturnType<typeof chatControllerGetMyChats>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMyChats>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Список моих чатов
 */

export function useChatControllerGetMyChats<
  TData = Awaited<ReturnType<typeof chatControllerGetMyChats>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMyChats>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getChatControllerGetMyChatsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary История сообщений чата
 */
export const chatControllerGetMessages = (
  params: ChatControllerGetMessagesParams,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<MessageResponseDto>(
    { url: `/api/chat/messages`, method: "GET", params, signal },
    options,
  );
};

export const getChatControllerGetMessagesInfiniteQueryKey = (
  params?: ChatControllerGetMessagesParams,
) => {
  return [
    "infinite",
    `/api/chat/messages`,
    ...(params ? [params] : []),
  ] as const;
};

export const getChatControllerGetMessagesQueryKey = (
  params?: ChatControllerGetMessagesParams,
) => {
  return [`/api/chat/messages`, ...(params ? [params] : [])] as const;
};

export const getChatControllerGetMessagesInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof chatControllerGetMessages>>,
    ChatControllerGetMessagesParams["skip"]
  >,
  TError = ErrorType<unknown>,
>(
  params: ChatControllerGetMessagesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMessages>>,
        TError,
        TData,
        QueryKey,
        ChatControllerGetMessagesParams["skip"]
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getChatControllerGetMessagesInfiniteQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof chatControllerGetMessages>>,
    QueryKey,
    ChatControllerGetMessagesParams["skip"]
  > = ({ signal, pageParam }) =>
    chatControllerGetMessages(
      { ...params, skip: pageParam || params?.["skip"] },
      requestOptions,
      signal,
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof chatControllerGetMessages>>,
    TError,
    TData,
    QueryKey,
    ChatControllerGetMessagesParams["skip"]
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChatControllerGetMessagesInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof chatControllerGetMessages>>
>;
export type ChatControllerGetMessagesInfiniteQueryError = ErrorType<unknown>;

export function useChatControllerGetMessagesInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof chatControllerGetMessages>>,
    ChatControllerGetMessagesParams["skip"]
  >,
  TError = ErrorType<unknown>,
>(
  params: ChatControllerGetMessagesParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMessages>>,
        TError,
        TData,
        QueryKey,
        ChatControllerGetMessagesParams["skip"]
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerGetMessages>>,
          TError,
          Awaited<ReturnType<typeof chatControllerGetMessages>>,
          QueryKey
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatControllerGetMessagesInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof chatControllerGetMessages>>,
    ChatControllerGetMessagesParams["skip"]
  >,
  TError = ErrorType<unknown>,
>(
  params: ChatControllerGetMessagesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMessages>>,
        TError,
        TData,
        QueryKey,
        ChatControllerGetMessagesParams["skip"]
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerGetMessages>>,
          TError,
          Awaited<ReturnType<typeof chatControllerGetMessages>>,
          QueryKey
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatControllerGetMessagesInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof chatControllerGetMessages>>,
    ChatControllerGetMessagesParams["skip"]
  >,
  TError = ErrorType<unknown>,
>(
  params: ChatControllerGetMessagesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMessages>>,
        TError,
        TData,
        QueryKey,
        ChatControllerGetMessagesParams["skip"]
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary История сообщений чата
 */

export function useChatControllerGetMessagesInfinite<
  TData = InfiniteData<
    Awaited<ReturnType<typeof chatControllerGetMessages>>,
    ChatControllerGetMessagesParams["skip"]
  >,
  TError = ErrorType<unknown>,
>(
  params: ChatControllerGetMessagesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMessages>>,
        TError,
        TData,
        QueryKey,
        ChatControllerGetMessagesParams["skip"]
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getChatControllerGetMessagesInfiniteQueryOptions(
    params,
    options,
  );

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getChatControllerGetMessagesQueryOptions = <
  TData = Awaited<ReturnType<typeof chatControllerGetMessages>>,
  TError = ErrorType<unknown>,
>(
  params: ChatControllerGetMessagesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMessages>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getChatControllerGetMessagesQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof chatControllerGetMessages>>
  > = ({ signal }) => chatControllerGetMessages(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof chatControllerGetMessages>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ChatControllerGetMessagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof chatControllerGetMessages>>
>;
export type ChatControllerGetMessagesQueryError = ErrorType<unknown>;

export function useChatControllerGetMessages<
  TData = Awaited<ReturnType<typeof chatControllerGetMessages>>,
  TError = ErrorType<unknown>,
>(
  params: ChatControllerGetMessagesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMessages>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerGetMessages>>,
          TError,
          Awaited<ReturnType<typeof chatControllerGetMessages>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatControllerGetMessages<
  TData = Awaited<ReturnType<typeof chatControllerGetMessages>>,
  TError = ErrorType<unknown>,
>(
  params: ChatControllerGetMessagesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMessages>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chatControllerGetMessages>>,
          TError,
          Awaited<ReturnType<typeof chatControllerGetMessages>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useChatControllerGetMessages<
  TData = Awaited<ReturnType<typeof chatControllerGetMessages>>,
  TError = ErrorType<unknown>,
>(
  params: ChatControllerGetMessagesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMessages>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary История сообщений чата
 */

export function useChatControllerGetMessages<
  TData = Awaited<ReturnType<typeof chatControllerGetMessages>>,
  TError = ErrorType<unknown>,
>(
  params: ChatControllerGetMessagesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof chatControllerGetMessages>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getChatControllerGetMessagesQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
