/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateTaskDto,
  TaskDto,
  TasksControllerFindAllParams,
  UpdateTaskDto,
} from "../../model";

import { createInstance } from "../../instance";
import type { ErrorType, BodyType } from "../../instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Создает задачу и привязывает её к текущему пользователю. Можно опционально привязать к сделке.
 * @summary Создать новую задачу
 */
export const tasksControllerCreate = (
  createTaskDto: BodyType<CreateTaskDto>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<TaskDto>(
    {
      url: `/tasks`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createTaskDto,
      signal,
    },
    options,
  );
};

export const getTasksControllerCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksControllerCreate>>,
    TError,
    { data: BodyType<CreateTaskDto> },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tasksControllerCreate>>,
  TError,
  { data: BodyType<CreateTaskDto> },
  TContext
> => {
  const mutationKey = ["tasksControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tasksControllerCreate>>,
    { data: BodyType<CreateTaskDto> }
  > = (props) => {
    const { data } = props ?? {};

    return tasksControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TasksControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tasksControllerCreate>>
>;
export type TasksControllerCreateMutationBody = BodyType<CreateTaskDto>;
export type TasksControllerCreateMutationError = ErrorType<unknown>;

/**
 * @summary Создать новую задачу
 */
export const useTasksControllerCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tasksControllerCreate>>,
      TError,
      { data: BodyType<CreateTaskDto> },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tasksControllerCreate>>,
  TError,
  { data: BodyType<CreateTaskDto> },
  TContext
> => {
  return useMutation(
    getTasksControllerCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * Возвращает все задачи текущего пользователя. Можно отфильтровать по конкретной сделке.
 * @summary Получить список задач
 */
export const tasksControllerFindAll = (
  params?: TasksControllerFindAllParams,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<TaskDto[]>(
    { url: `/tasks`, method: "GET", params, signal },
    options,
  );
};

export const getTasksControllerFindAllQueryKey = (
  params?: TasksControllerFindAllParams,
) => {
  return [`/tasks`, ...(params ? [params] : [])] as const;
};

export const getTasksControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof tasksControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params?: TasksControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tasksControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getTasksControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof tasksControllerFindAll>>
  > = ({ signal }) => tasksControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof tasksControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TasksControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof tasksControllerFindAll>>
>;
export type TasksControllerFindAllQueryError = ErrorType<unknown>;

export function useTasksControllerFindAll<
  TData = Awaited<ReturnType<typeof tasksControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | TasksControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tasksControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof tasksControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof tasksControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTasksControllerFindAll<
  TData = Awaited<ReturnType<typeof tasksControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params?: TasksControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tasksControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof tasksControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof tasksControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useTasksControllerFindAll<
  TData = Awaited<ReturnType<typeof tasksControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params?: TasksControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tasksControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить список задач
 */

export function useTasksControllerFindAll<
  TData = Awaited<ReturnType<typeof tasksControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params?: TasksControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof tasksControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getTasksControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Позволяет изменить заголовок, описание, дату дедлайна или статус выполнения.
 * @summary Обновить данные задачи
 */
export const tasksControllerUpdate = (
  id: number,
  updateTaskDto: BodyType<UpdateTaskDto>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    {
      url: `/tasks/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateTaskDto,
      signal,
    },
    options,
  );
};

export const getTasksControllerUpdateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksControllerUpdate>>,
    TError,
    { id: number; data: BodyType<UpdateTaskDto> },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tasksControllerUpdate>>,
  TError,
  { id: number; data: BodyType<UpdateTaskDto> },
  TContext
> => {
  const mutationKey = ["tasksControllerUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tasksControllerUpdate>>,
    { id: number; data: BodyType<UpdateTaskDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return tasksControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TasksControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof tasksControllerUpdate>>
>;
export type TasksControllerUpdateMutationBody = BodyType<UpdateTaskDto>;
export type TasksControllerUpdateMutationError = ErrorType<void>;

/**
 * @summary Обновить данные задачи
 */
export const useTasksControllerUpdate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tasksControllerUpdate>>,
      TError,
      { id: number; data: BodyType<UpdateTaskDto> },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tasksControllerUpdate>>,
  TError,
  { id: number; data: BodyType<UpdateTaskDto> },
  TContext
> => {
  return useMutation(
    getTasksControllerUpdateMutationOptions(options),
    queryClient,
  );
};
/**
 * Безвозвратно удаляет задачу из системы.
 * @summary Удалить задачу
 */
export const tasksControllerRemove = (
  id: number,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    { url: `/tasks/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getTasksControllerRemoveMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksControllerRemove>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tasksControllerRemove>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["tasksControllerRemove"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tasksControllerRemove>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return tasksControllerRemove(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TasksControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof tasksControllerRemove>>
>;

export type TasksControllerRemoveMutationError = ErrorType<unknown>;

/**
 * @summary Удалить задачу
 */
export const useTasksControllerRemove = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tasksControllerRemove>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tasksControllerRemove>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(
    getTasksControllerRemoveMutationOptions(options),
    queryClient,
  );
};
/**
 * Быстро меняет статус задачи с "выполнено" на "не выполнено" и наоборот.
 * @summary Переключить статус выполнения
 */
export const tasksControllerToggleStatus = (
  id: number,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    { url: `/tasks/${id}/toggle`, method: "PATCH", signal },
    options,
  );
};

export const getTasksControllerToggleStatusMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof tasksControllerToggleStatus>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof tasksControllerToggleStatus>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["tasksControllerToggleStatus"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof tasksControllerToggleStatus>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return tasksControllerToggleStatus(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type TasksControllerToggleStatusMutationResult = NonNullable<
  Awaited<ReturnType<typeof tasksControllerToggleStatus>>
>;

export type TasksControllerToggleStatusMutationError = ErrorType<unknown>;

/**
 * @summary Переключить статус выполнения
 */
export const useTasksControllerToggleStatus = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof tasksControllerToggleStatus>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof tasksControllerToggleStatus>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(
    getTasksControllerToggleStatusMutationOptions(options),
    queryClient,
  );
};
