/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { CreateContactDto, UpdateContactDto } from "../../model";

import { createInstance } from "../../instance";
import type { ErrorType, BodyType } from "../../instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Создать новый контакт
 */
export const contactControllerCreate = (
  createContactDto: BodyType<CreateContactDto>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    {
      url: `/contacts`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createContactDto,
      signal,
    },
    options,
  );
};

export const getContactControllerCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contactControllerCreate>>,
    TError,
    { data: BodyType<CreateContactDto> },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contactControllerCreate>>,
  TError,
  { data: BodyType<CreateContactDto> },
  TContext
> => {
  const mutationKey = ["contactControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contactControllerCreate>>,
    { data: BodyType<CreateContactDto> }
  > = (props) => {
    const { data } = props ?? {};

    return contactControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContactControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof contactControllerCreate>>
>;
export type ContactControllerCreateMutationBody = BodyType<CreateContactDto>;
export type ContactControllerCreateMutationError = ErrorType<void>;

/**
 * @summary Создать новый контакт
 */
export const useContactControllerCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof contactControllerCreate>>,
      TError,
      { data: BodyType<CreateContactDto> },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof contactControllerCreate>>,
  TError,
  { data: BodyType<CreateContactDto> },
  TContext
> => {
  return useMutation(
    getContactControllerCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Получить все контакты
 */
export const contactControllerFindAll = (
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    { url: `/contacts`, method: "GET", signal },
    options,
  );
};

export const getContactControllerFindAllQueryKey = () => {
  return [`/contacts`] as const;
};

export const getContactControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof contactControllerFindAll>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof contactControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getContactControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof contactControllerFindAll>>
  > = ({ signal }) => contactControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof contactControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ContactControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof contactControllerFindAll>>
>;
export type ContactControllerFindAllQueryError = ErrorType<unknown>;

export function useContactControllerFindAll<
  TData = Awaited<ReturnType<typeof contactControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contactControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof contactControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useContactControllerFindAll<
  TData = Awaited<ReturnType<typeof contactControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contactControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof contactControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useContactControllerFindAll<
  TData = Awaited<ReturnType<typeof contactControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить все контакты
 */

export function useContactControllerFindAll<
  TData = Awaited<ReturnType<typeof contactControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getContactControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Получить контакт по ID
 */
export const contactControllerFindOne = (
  id: number,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    { url: `/contacts/${id}`, method: "GET", signal },
    options,
  );
};

export const getContactControllerFindOneQueryKey = (id: number) => {
  return [`/contacts/${id}`] as const;
};

export const getContactControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof contactControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getContactControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof contactControllerFindOne>>
  > = ({ signal }) => contactControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof contactControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ContactControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof contactControllerFindOne>>
>;
export type ContactControllerFindOneQueryError = ErrorType<void>;

export function useContactControllerFindOne<
  TData = Awaited<ReturnType<typeof contactControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof contactControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof contactControllerFindOne>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useContactControllerFindOne<
  TData = Awaited<ReturnType<typeof contactControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof contactControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof contactControllerFindOne>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useContactControllerFindOne<
  TData = Awaited<ReturnType<typeof contactControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить контакт по ID
 */

export function useContactControllerFindOne<
  TData = Awaited<ReturnType<typeof contactControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof contactControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getContactControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Обновить данные контакта
 */
export const contactControllerUpdate = (
  id: number,
  updateContactDto: BodyType<UpdateContactDto>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    {
      url: `/contacts/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateContactDto,
      signal,
    },
    options,
  );
};

export const getContactControllerUpdateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contactControllerUpdate>>,
    TError,
    { id: number; data: BodyType<UpdateContactDto> },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contactControllerUpdate>>,
  TError,
  { id: number; data: BodyType<UpdateContactDto> },
  TContext
> => {
  const mutationKey = ["contactControllerUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contactControllerUpdate>>,
    { id: number; data: BodyType<UpdateContactDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return contactControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContactControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof contactControllerUpdate>>
>;
export type ContactControllerUpdateMutationBody = BodyType<UpdateContactDto>;
export type ContactControllerUpdateMutationError = ErrorType<void>;

/**
 * @summary Обновить данные контакта
 */
export const useContactControllerUpdate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof contactControllerUpdate>>,
      TError,
      { id: number; data: BodyType<UpdateContactDto> },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof contactControllerUpdate>>,
  TError,
  { id: number; data: BodyType<UpdateContactDto> },
  TContext
> => {
  return useMutation(
    getContactControllerUpdateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Удалить контакт
 */
export const contactControllerRemove = (
  id: number,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    { url: `/contacts/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getContactControllerRemoveMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof contactControllerRemove>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof contactControllerRemove>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["contactControllerRemove"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof contactControllerRemove>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return contactControllerRemove(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ContactControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof contactControllerRemove>>
>;

export type ContactControllerRemoveMutationError = ErrorType<unknown>;

/**
 * @summary Удалить контакт
 */
export const useContactControllerRemove = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof contactControllerRemove>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof contactControllerRemove>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(
    getContactControllerRemoveMutationOptions(options),
    queryClient,
  );
};
