/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ChangePasswordDto,
  ForgotPasswordDto,
  GetSessionInfoDto,
  ResetPasswordConfirmDto,
  SignInBodyDto,
  SignUpBodyDto,
} from "../../model";

import { createInstance } from "../../instance";
import type { ErrorType, BodyType } from "../../instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary регистрация
 */
export const authControllerSignUp = (
  signUpBodyDto: BodyType<SignUpBodyDto>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    {
      url: `/auth/sign-up`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: signUpBodyDto,
      signal,
    },
    options,
  );
};

export const getAuthControllerSignUpMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSignUp>>,
    TError,
    { data: BodyType<SignUpBodyDto> },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerSignUp>>,
  TError,
  { data: BodyType<SignUpBodyDto> },
  TContext
> => {
  const mutationKey = ["authControllerSignUp"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerSignUp>>,
    { data: BodyType<SignUpBodyDto> }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerSignUp(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerSignUpMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignUp>>
>;
export type AuthControllerSignUpMutationBody = BodyType<SignUpBodyDto>;
export type AuthControllerSignUpMutationError = ErrorType<unknown>;

/**
 * @summary регистрация
 */
export const useAuthControllerSignUp = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerSignUp>>,
      TError,
      { data: BodyType<SignUpBodyDto> },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerSignUp>>,
  TError,
  { data: BodyType<SignUpBodyDto> },
  TContext
> => {
  return useMutation(
    getAuthControllerSignUpMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary авторизация
 */
export const authControllerSignIn = (
  signInBodyDto: BodyType<SignInBodyDto>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    {
      url: `/auth/sign-in`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: signInBodyDto,
      signal,
    },
    options,
  );
};

export const getAuthControllerSignInMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSignIn>>,
    TError,
    { data: BodyType<SignInBodyDto> },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerSignIn>>,
  TError,
  { data: BodyType<SignInBodyDto> },
  TContext
> => {
  const mutationKey = ["authControllerSignIn"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerSignIn>>,
    { data: BodyType<SignInBodyDto> }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerSignIn(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerSignInMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignIn>>
>;
export type AuthControllerSignInMutationBody = BodyType<SignInBodyDto>;
export type AuthControllerSignInMutationError = ErrorType<unknown>;

/**
 * @summary авторизация
 */
export const useAuthControllerSignIn = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerSignIn>>,
      TError,
      { data: BodyType<SignInBodyDto> },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerSignIn>>,
  TError,
  { data: BodyType<SignInBodyDto> },
  TContext
> => {
  return useMutation(
    getAuthControllerSignInMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary выход из аккаунта
 */
export const authControllerSignOut = (
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    { url: `/auth/sign-out`, method: "POST", signal },
    options,
  );
};

export const getAuthControllerSignOutMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerSignOut>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerSignOut>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authControllerSignOut"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerSignOut>>,
    void
  > = () => {
    return authControllerSignOut(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerSignOutMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerSignOut>>
>;

export type AuthControllerSignOutMutationError = ErrorType<unknown>;

/**
 * @summary выход из аккаунта
 */
export const useAuthControllerSignOut = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerSignOut>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerSignOut>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getAuthControllerSignOutMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary инофрмацию о сессии
 */
export const authControllerGetSessionInfo = (
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<GetSessionInfoDto>(
    { url: `/auth/session`, method: "GET", signal },
    options,
  );
};

export const getAuthControllerGetSessionInfoQueryKey = () => {
  return [`/auth/session`] as const;
};

export const getAuthControllerGetSessionInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAuthControllerGetSessionInfoQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authControllerGetSessionInfo>>
  > = ({ signal }) => authControllerGetSessionInfo(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthControllerGetSessionInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetSessionInfo>>
>;
export type AuthControllerGetSessionInfoQueryError = ErrorType<unknown>;

export function useAuthControllerGetSessionInfo<
  TData = Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetSessionInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthControllerGetSessionInfo<
  TData = Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetSessionInfo>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthControllerGetSessionInfo<
  TData = Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary инофрмацию о сессии
 */

export function useAuthControllerGetSessionInfo<
  TData = Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetSessionInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAuthControllerGetSessionInfoQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary изменить пароль профиля
 */
export const authControllerChangePassword = (
  changePasswordDto: BodyType<ChangePasswordDto>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    {
      url: `/auth/change-password`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: changePasswordDto,
      signal,
    },
    options,
  );
};

export const getAuthControllerChangePasswordMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerChangePassword>>,
    TError,
    { data: BodyType<ChangePasswordDto> },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerChangePassword>>,
  TError,
  { data: BodyType<ChangePasswordDto> },
  TContext
> => {
  const mutationKey = ["authControllerChangePassword"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerChangePassword>>,
    { data: BodyType<ChangePasswordDto> }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerChangePassword(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerChangePasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerChangePassword>>
>;
export type AuthControllerChangePasswordMutationBody =
  BodyType<ChangePasswordDto>;
export type AuthControllerChangePasswordMutationError = ErrorType<unknown>;

/**
 * @summary изменить пароль профиля
 */
export const useAuthControllerChangePassword = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerChangePassword>>,
      TError,
      { data: BodyType<ChangePasswordDto> },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerChangePassword>>,
  TError,
  { data: BodyType<ChangePasswordDto> },
  TContext
> => {
  return useMutation(
    getAuthControllerChangePasswordMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary функция "забытый пароль"
 */
export const authControllerForgotPassword = (
  forgotPasswordDto: BodyType<ForgotPasswordDto>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    {
      url: `/auth/forgot-password`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: forgotPasswordDto,
      signal,
    },
    options,
  );
};

export const getAuthControllerForgotPasswordMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerForgotPassword>>,
    TError,
    { data: BodyType<ForgotPasswordDto> },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerForgotPassword>>,
  TError,
  { data: BodyType<ForgotPasswordDto> },
  TContext
> => {
  const mutationKey = ["authControllerForgotPassword"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerForgotPassword>>,
    { data: BodyType<ForgotPasswordDto> }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerForgotPassword(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerForgotPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerForgotPassword>>
>;
export type AuthControllerForgotPasswordMutationBody =
  BodyType<ForgotPasswordDto>;
export type AuthControllerForgotPasswordMutationError = ErrorType<unknown>;

/**
 * @summary функция "забытый пароль"
 */
export const useAuthControllerForgotPassword = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerForgotPassword>>,
      TError,
      { data: BodyType<ForgotPasswordDto> },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerForgotPassword>>,
  TError,
  { data: BodyType<ForgotPasswordDto> },
  TContext
> => {
  return useMutation(
    getAuthControllerForgotPasswordMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary перезапись пароля
 */
export const authControllerResetPasswordConfirm = (
  resetPasswordConfirmDto: BodyType<ResetPasswordConfirmDto>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    {
      url: `/auth/reset-password-confirm`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: resetPasswordConfirmDto,
      signal,
    },
    options,
  );
};

export const getAuthControllerResetPasswordConfirmMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerResetPasswordConfirm>>,
    TError,
    { data: BodyType<ResetPasswordConfirmDto> },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerResetPasswordConfirm>>,
  TError,
  { data: BodyType<ResetPasswordConfirmDto> },
  TContext
> => {
  const mutationKey = ["authControllerResetPasswordConfirm"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerResetPasswordConfirm>>,
    { data: BodyType<ResetPasswordConfirmDto> }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerResetPasswordConfirm(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerResetPasswordConfirmMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerResetPasswordConfirm>>
>;
export type AuthControllerResetPasswordConfirmMutationBody =
  BodyType<ResetPasswordConfirmDto>;
export type AuthControllerResetPasswordConfirmMutationError =
  ErrorType<unknown>;

/**
 * @summary перезапись пароля
 */
export const useAuthControllerResetPasswordConfirm = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerResetPasswordConfirm>>,
      TError,
      { data: BodyType<ResetPasswordConfirmDto> },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerResetPasswordConfirm>>,
  TError,
  { data: BodyType<ResetPasswordConfirmDto> },
  TContext
> => {
  return useMutation(
    getAuthControllerResetPasswordConfirmMutationOptions(options),
    queryClient,
  );
};
