/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type { PhotoControllerUploadChatFilesBody } from "../../model";

import { createInstance } from "../../instance";
import type { ErrorType, BodyType } from "../../instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Загрузить файлы для сообщения в чате
 */
export const photoControllerUploadChatFiles = (
  photoControllerUploadChatFilesBody: BodyType<PhotoControllerUploadChatFilesBody>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  photoControllerUploadChatFilesBody.files.forEach((value) =>
    formData.append(`files`, value),
  );

  return createInstance<void>(
    { url: `/photos/chat`, method: "POST", data: formData, signal },
    options,
  );
};

export const getPhotoControllerUploadChatFilesMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof photoControllerUploadChatFiles>>,
    TError,
    { data: BodyType<PhotoControllerUploadChatFilesBody> },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof photoControllerUploadChatFiles>>,
  TError,
  { data: BodyType<PhotoControllerUploadChatFilesBody> },
  TContext
> => {
  const mutationKey = ["photoControllerUploadChatFiles"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof photoControllerUploadChatFiles>>,
    { data: BodyType<PhotoControllerUploadChatFilesBody> }
  > = (props) => {
    const { data } = props ?? {};

    return photoControllerUploadChatFiles(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PhotoControllerUploadChatFilesMutationResult = NonNullable<
  Awaited<ReturnType<typeof photoControllerUploadChatFiles>>
>;
export type PhotoControllerUploadChatFilesMutationBody =
  BodyType<PhotoControllerUploadChatFilesBody>;
export type PhotoControllerUploadChatFilesMutationError = ErrorType<unknown>;

/**
 * @summary Загрузить файлы для сообщения в чате
 */
export const usePhotoControllerUploadChatFiles = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof photoControllerUploadChatFiles>>,
      TError,
      { data: BodyType<PhotoControllerUploadChatFilesBody> },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof photoControllerUploadChatFiles>>,
  TError,
  { data: BodyType<PhotoControllerUploadChatFilesBody> },
  TContext
> => {
  return useMutation(
    getPhotoControllerUploadChatFilesMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Удалить фото
 */
export const photoControllerRemovePhoto = (
  id: number,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    { url: `/photos/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getPhotoControllerRemovePhotoMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof photoControllerRemovePhoto>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof photoControllerRemovePhoto>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["photoControllerRemovePhoto"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof photoControllerRemovePhoto>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return photoControllerRemovePhoto(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PhotoControllerRemovePhotoMutationResult = NonNullable<
  Awaited<ReturnType<typeof photoControllerRemovePhoto>>
>;

export type PhotoControllerRemovePhotoMutationError = ErrorType<unknown>;

/**
 * @summary Удалить фото
 */
export const usePhotoControllerRemovePhoto = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof photoControllerRemovePhoto>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof photoControllerRemovePhoto>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(
    getPhotoControllerRemovePhotoMutationOptions(options),
    queryClient,
  );
};
