/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */
import type { ActivityDtoType } from "./activityDtoType";
import type { ActivityUserDto } from "./activityUserDto";

export interface ActivityDto {
  id: number;
  type: ActivityDtoType;
  content: string;
  createdAt: string;
  user: ActivityUserDto;
  companyId?: number;
  dealId?: number;
  userId: number;
}
