/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */
import type { AvatarDto } from "./avatarDto";
import type { ChatMemberDto } from "./chatMemberDto";
import type { MessageDto } from "./messageDto";

export interface ChatResponseDto {
  id: number;
  title?: string;
  isGroup: boolean;
  lastMessage: MessageDto | null;
  avatar?: AvatarDto;
  members: ChatMemberDto[];
}
