/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */

export interface CreateMessageDto {
  /** Текст сообщения */
  text: string;
  /** ID прикрепленных файлов */
  fileIds?: number[];
  /** ID сделки */
  dealId?: number;
}
