/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */
import type { CreateDealDtoStatus } from "./createDealDtoStatus";

export interface CreateDealDto {
  /** Название сделки */
  title: string;
  /** Сумма сделки */
  amount: number;
  /** ID компании */
  companyId: number;
  /** ID контактного лица */
  contactId?: number;
  /** ID владельца (User) */
  ownerId: number;
  status: CreateDealDtoStatus;
}
