/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */

export type CreateDealDtoStatus =
  (typeof CreateDealDtoStatus)[keyof typeof CreateDealDtoStatus];

export const CreateDealDtoStatus = {
  NEW: "NEW",
  QUALIFICATION: "QUALIFICATION",
  PROPOSAL: "PROPOSAL",
  NEGOTIATION: "NEGOTIATION",
  CLOSED_WON: "CLOSED_WON",
  CLOSED_LOST: "CLOSED_LOST",
} as const;
