/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */

export interface TaskDto {
  id: number;
  title: string;
  /** @nullable */
  description: string | null;
  dueDate: string;
  isCompleted: boolean;
  userId: number;
  /** @nullable */
  dealId: number | null;
  createdAt: string;
}
