/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { ActivityControllerFindAllParams } from "../../model";

import { createInstance } from "../../instance";
import type { ErrorType } from "../../instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Получить ленту событий
 */
export const activityControllerFindAll = (
  params?: ActivityControllerFindAllParams,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    { url: `/activity`, method: "GET", params, signal },
    options,
  );
};

export const getActivityControllerFindAllQueryKey = (
  params?: ActivityControllerFindAllParams,
) => {
  return [`/activity`, ...(params ? [params] : [])] as const;
};

export const getActivityControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof activityControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params?: ActivityControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof activityControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getActivityControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof activityControllerFindAll>>
  > = ({ signal }) => activityControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof activityControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ActivityControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof activityControllerFindAll>>
>;
export type ActivityControllerFindAllQueryError = ErrorType<unknown>;

export function useActivityControllerFindAll<
  TData = Awaited<ReturnType<typeof activityControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: undefined | ActivityControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof activityControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof activityControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof activityControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useActivityControllerFindAll<
  TData = Awaited<ReturnType<typeof activityControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params?: ActivityControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof activityControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof activityControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof activityControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useActivityControllerFindAll<
  TData = Awaited<ReturnType<typeof activityControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params?: ActivityControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof activityControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Получить ленту событий
 */

export function useActivityControllerFindAll<
  TData = Awaited<ReturnType<typeof activityControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params?: ActivityControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof activityControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getActivityControllerFindAllQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
