/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */
import { useInfiniteQuery, useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type { CreateDealDto, UpdateDealDto } from "../../model";

import { createInstance } from "../../instance";
import type { ErrorType, BodyType } from "../../instance";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Создать новую сделку
 */
export const dealControllerCreate = (
  createDealDto: BodyType<CreateDealDto>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    {
      url: `/api/deals`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createDealDto,
      signal,
    },
    options,
  );
};

export const getDealControllerCreateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof dealControllerCreate>>,
    TError,
    { data: BodyType<CreateDealDto> },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof dealControllerCreate>>,
  TError,
  { data: BodyType<CreateDealDto> },
  TContext
> => {
  const mutationKey = ["dealControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dealControllerCreate>>,
    { data: BodyType<CreateDealDto> }
  > = (props) => {
    const { data } = props ?? {};

    return dealControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DealControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof dealControllerCreate>>
>;
export type DealControllerCreateMutationBody = BodyType<CreateDealDto>;
export type DealControllerCreateMutationError = ErrorType<unknown>;

/**
 * @summary Создать новую сделку
 */
export const useDealControllerCreate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof dealControllerCreate>>,
      TError,
      { data: BodyType<CreateDealDto> },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof dealControllerCreate>>,
  TError,
  { data: BodyType<CreateDealDto> },
  TContext
> => {
  return useMutation(
    getDealControllerCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Список всех сделок
 */
export const dealControllerFindAll = (
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    { url: `/api/deals`, method: "GET", signal },
    options,
  );
};

export const getDealControllerFindAllInfiniteQueryKey = () => {
  return ["infinite", `/api/deals`] as const;
};

export const getDealControllerFindAllQueryKey = () => {
  return [`/api/deals`] as const;
};

export const getDealControllerFindAllInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof dealControllerFindAll>>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof dealControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDealControllerFindAllInfiniteQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof dealControllerFindAll>>
  > = ({ signal }) => dealControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof dealControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DealControllerFindAllInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof dealControllerFindAll>>
>;
export type DealControllerFindAllInfiniteQueryError = ErrorType<unknown>;

export function useDealControllerFindAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof dealControllerFindAll>>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof dealControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dealControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof dealControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDealControllerFindAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof dealControllerFindAll>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof dealControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dealControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof dealControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDealControllerFindAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof dealControllerFindAll>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof dealControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Список всех сделок
 */

export function useDealControllerFindAllInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof dealControllerFindAll>>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof dealControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDealControllerFindAllInfiniteQueryOptions(options);

  const query = useInfiniteQuery(
    queryOptions,
    queryClient,
  ) as UseInfiniteQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getDealControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof dealControllerFindAll>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof dealControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDealControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof dealControllerFindAll>>
  > = ({ signal }) => dealControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof dealControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DealControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof dealControllerFindAll>>
>;
export type DealControllerFindAllQueryError = ErrorType<unknown>;

export function useDealControllerFindAll<
  TData = Awaited<ReturnType<typeof dealControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dealControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dealControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof dealControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDealControllerFindAll<
  TData = Awaited<ReturnType<typeof dealControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dealControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dealControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof dealControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useDealControllerFindAll<
  TData = Awaited<ReturnType<typeof dealControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dealControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Список всех сделок
 */

export function useDealControllerFindAll<
  TData = Awaited<ReturnType<typeof dealControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof dealControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getDealControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Обновить статус или данные сделки
 */
export const dealControllerUpdate = (
  id: number,
  updateDealDto: BodyType<UpdateDealDto>,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    {
      url: `/api/deals/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateDealDto,
      signal,
    },
    options,
  );
};

export const getDealControllerUpdateMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof dealControllerUpdate>>,
    TError,
    { id: number; data: BodyType<UpdateDealDto> },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof dealControllerUpdate>>,
  TError,
  { id: number; data: BodyType<UpdateDealDto> },
  TContext
> => {
  const mutationKey = ["dealControllerUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dealControllerUpdate>>,
    { id: number; data: BodyType<UpdateDealDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return dealControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DealControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof dealControllerUpdate>>
>;
export type DealControllerUpdateMutationBody = BodyType<UpdateDealDto>;
export type DealControllerUpdateMutationError = ErrorType<unknown>;

/**
 * @summary Обновить статус или данные сделки
 */
export const useDealControllerUpdate = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof dealControllerUpdate>>,
      TError,
      { id: number; data: BodyType<UpdateDealDto> },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof dealControllerUpdate>>,
  TError,
  { id: number; data: BodyType<UpdateDealDto> },
  TContext
> => {
  return useMutation(
    getDealControllerUpdateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Удалить сделку
 */
export const dealControllerDelete = (
  id: number,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    { url: `/api/deals/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getDealControllerDeleteMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof dealControllerDelete>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof dealControllerDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["dealControllerDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dealControllerDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return dealControllerDelete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DealControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof dealControllerDelete>>
>;

export type DealControllerDeleteMutationError = ErrorType<unknown>;

/**
 * @summary Удалить сделку
 */
export const useDealControllerDelete = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof dealControllerDelete>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof dealControllerDelete>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(
    getDealControllerDeleteMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary Загрузить документы к сделке
 */
export const dealControllerUploadDealFiles = (
  id: number,
  options?: SecondParameter<typeof createInstance>,
  signal?: AbortSignal,
) => {
  return createInstance<void>(
    { url: `/api/deals/${id}/upload`, method: "POST", signal },
    options,
  );
};

export const getDealControllerUploadDealFilesMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof dealControllerUploadDealFiles>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof createInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof dealControllerUploadDealFiles>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["dealControllerUploadDealFiles"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dealControllerUploadDealFiles>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return dealControllerUploadDealFiles(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DealControllerUploadDealFilesMutationResult = NonNullable<
  Awaited<ReturnType<typeof dealControllerUploadDealFiles>>
>;

export type DealControllerUploadDealFilesMutationError = ErrorType<unknown>;

/**
 * @summary Загрузить документы к сделке
 */
export const useDealControllerUploadDealFiles = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof dealControllerUploadDealFiles>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof createInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof dealControllerUploadDealFiles>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(
    getDealControllerUploadDealFilesMutationOptions(options),
    queryClient,
  );
};
