/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */

export type ActivityDtoType =
  (typeof ActivityDtoType)[keyof typeof ActivityDtoType];

export const ActivityDtoType = {
  COMMENT: "COMMENT",
  STAGE_CHANGE: "STAGE_CHANGE",
  VALUE_CHANGE: "VALUE_CHANGE",
  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_DELETED: "TASK_DELETED",
  FILE_ADDED: "FILE_ADDED",
  CHAT_MESSAGE: "CHAT_MESSAGE",
} as const;
