/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */

export type ActivityControllerFindAllParams = {
  /**
   * Фильтр по сделке
   */
  dealId?: string;
  /**
   * Фильтр по компании
   */
  companyId?: string;
};
