/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */
import type { AuthorDto } from "./authorDto";
import type { AvatarDto } from "./avatarDto";

export interface ChatResponseDto {
  id: number;
  title?: string;
  isGroup: boolean;
  avatar?: AvatarDto;
  members: AuthorDto[];
}
