/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */

export type CompanyControllerFindAllParams = {
  skip: number;
  /**
   * ID последней компании с предыдущей страницы
   */
  cursor?: number;
  /**
   * Количество записей
   */
  limit?: number;
};
