/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */
import type { CreateCompanyDto } from "./createCompanyDto";

export type CompanyControllerFindAll200 = {
  data?: CreateCompanyDto[];
  /** @nullable */
  nextCursor?: number | null;
};
