/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */

export interface CreateContactDto {
  /** Имя контакта */
  firstName: string;
  /** Фамилия контакта */
  lastName: string;
  /** Email должен быть уникальным */
  email: string;
  /** Номер телефона */
  phone?: string;
  /** ID компании, к которой привязан контакт */
  companyId: number;
}
