/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */
import type { AuthorDto } from "./authorDto";

export interface MessageDto {
  id: number;
  text: string;
  createdAt: string;
  author: AuthorDto;
}
