/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */

export type TasksControllerFindAllParams = {
  /**
   * ID сделки для фильтрации задач
   */
  dealId?: string;
};
