/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * My Backend
 * Этот API работает с несколькими сущностями
 * OpenAPI spec version: 1.0
 */
import type { PhotoDto } from "./photoDto";

export interface UserDto {
  id: number;
  email: string;
  name?: string;
  photo: PhotoDto | null;
}
